language: r
sudo: false
cache: packages
dist: trusty
r:
  - release

addons:
  apt:
    packages:
      - libgsl0-dev

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - secure: "d0xff7hriQyReF4y3/iR5sHJlXocKNKcN6/Gi/r9Hxsfuh2Hx3fouQCMSPP+Oba6MDgEvAfryToAxcmaoZByQMwgevB0OBy5xkatj3oTHmhN5Nbk3jNXxXfA6P0Oqxaf7lXVZk2+Ly+PWnbgXn0uhjzdaZo0cWtVJ660ajS0x9Q="

warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"

r_github_packages:
  - berndbischl/BBmisc
## The following will return when my PRs are merged
#  - berndbischl/ParamHelpers
  - mlr-org/mlr
  - jimhester/lintr
  - mb706/covr

before_install:
  # we want to see libpaths and installed packages from cache
  - Rscript -e 'message("LIBPATHS:"); .libPaths()'
  - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,1:3]'

before_script:
  - Rscript -e 'install.packages("roxygen2")'
  - Rscript -e 'devtools::install_github("berndbischl/ParamHelpers", ref = "paramSetSugar")'
  - R --no-save <<< 'library("devtools"); document()'

script:
  - R CMD build .
  - travis_wait 100 R CMD check mlrCPO*.tar.gz --as-cran --run-donttest
  - grep -q -R "WARNING" "mlrCPO.Rcheck/00check.log" ; [ $? -ne 0 ]

after_success:
  - travis_wait 100 Rscript -e 'library(BBmisc);covr::codecov(quiet=FALSE)'
  - git checkout master
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - R --no-save <<< 'library("devtools"); document(); build_vignettes();'
  - git config user.name $GN
  - git config user.email $GM
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GT:@github.com" >> .git/credentials
  - git config push.default matching
  - git add --force man/*
  - git add --force inst/doc/*.html
  - git commit man inst DESCRIPTION NAMESPACE -m "update auto-generated documentation [ci skip]" || true
  - git push
  - "[ $TRAVIS_PULL_REQUEST == \"false\" -a $TRAVIS_BRANCH == \"master\" ] && curl -s -X POST -H \"Content-Type:application/json\" -H \"Accept:application/json\" -H \"Travis-API-Version:3\" -H \"Authorization:token $TT\" -d \"{\\\"request\\\":{\\\"branch\\\":\\\"gh-pages\\\", \\\"message\\\":\\\"commit $TRAVIS_COMMIT $TRAVIS_COMMIT_MSG\\\"}}\" https://api.travis-ci.org/repo/mlr-org%2Fmlr-tutorial/requests"

after_failure:
  - ./travis-tool.sh dump_logs

on_success: change
on_failure: always

